spring:
  datasource:
    url: jdbc:postgresql://${SERVER_HOST:localhost}:${SERVER_PORT:5432}/fitness-micro-user
    username: ${DB_USER:admin}
    password: ${DB_PASS:admin123}

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka/

server:
  port: 8081