spring:
  application:
   name: userservice
  datasource:
    url: jdbc:postgresql://192.168.1.106:5432/fitness-micro-user
    username: ${DB_USER:admin}
    password: ${DB_PASS:admin123}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8081
